// Generated by scripts/generate-account-contract.ts. Edit packages/accounts/schema/primitives.json.
#![allow(dead_code)]
#[derive(Debug, Clone, serde::Serialize)]
pub(crate) struct SafeInteger(u64);
impl<'de> serde::Deserialize<'de> for SafeInteger {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let n = <f64 as serde::Deserialize>::deserialize(deserializer)?;
        if !n.is_finite() || n < 0.0 || n.fract() != 0.0 || n > 9_007_199_254_740_991.0 {
            return Err(serde::de::Error::custom("unsafe integer"));
        }
        Ok(Self(n as u64))
    }
}
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct Profile {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) display_name: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackUser {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) profile: Option<Profile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) real_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) name: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackChannelId {
    pub(crate) id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackBotProfile {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) name: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackMessage {
    pub(crate) ts: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) user: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) channel: Option<SlackChannelId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) bot_profile: Option<SlackBotProfile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) username: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackRoom {
    pub(crate) id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) is_member: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) is_im: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) is_mpim: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) user: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) is_archived: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) unread_count: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) latest: Option<SlackMessage>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub(crate) enum SlackMarkerUpdated {
    V0(String),
    V1(f64),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub(crate) enum SlackMarkerHistoryInvalid {
    V0(String),
    V1(f64),
    V2(bool),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackMarker {
    pub(crate) id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) latest: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) updated: Option<SlackMarkerUpdated>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) history_invalid: Option<SlackMarkerHistoryInvalid>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) next_cursor: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackPagination {
    pub(crate) page_count: SafeInteger,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackMatches {
    pub(crate) matches: Vec<SlackMessage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) pagination: Option<SlackPagination>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoLatest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) sent_at: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) message: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoRoom {
    pub(crate) chat_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) r#type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) last_message: Option<KakaoLatest>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) unread_count: Option<f64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoMember {
    pub(crate) user_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) nickname: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum AccountMessageAuthorKind {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "chat")]
    Chat,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct AccountMessage {
    pub(crate) id: String,
    pub(crate) chat_id: String,
    pub(crate) author_id: String,
    pub(crate) author_name: String,
    pub(crate) ts: f64,
    pub(crate) body: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) author_kind: Option<AccountMessageAuthorKind>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct AccountChat {
    pub(crate) chat_id: String,
    pub(crate) title: String,
    pub(crate) latest_ts: f64,
    pub(crate) preview: String,
    pub(crate) can_send: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) unread: Option<f64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackPostedMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) ts: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) user: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) channel: Option<SlackChannelId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) bot_profile: Option<SlackBotProfile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) username: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackListedUser {
    pub(crate) id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) profile: Option<Profile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) real_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) name: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct LocalAttachment {
    pub(crate) path: String,
    pub(crate) name: String,
    pub(crate) size: SafeInteger,
    pub(crate) sha256: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackUsersListParams {
    pub(crate) limit: SafeInteger,
    pub(crate) cursor: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackUsersListResultData {
    pub(crate) members: Vec<SlackListedUser>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) response_metadata: Option<SlackMetadata>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackUsersListResult {
    pub(crate) data: SlackUsersListResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackUsersInfoParams {
    pub(crate) user: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackUsersInfoResultData {
    pub(crate) user: SlackUser,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackUsersInfoResult {
    pub(crate) data: SlackUsersInfoResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackClientCountsParams {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackClientCountsResultData {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) channels: Option<Vec<SlackMarker>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) ims: Option<Vec<SlackMarker>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) mpims: Option<Vec<SlackMarker>>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackClientCountsResult {
    pub(crate) data: SlackClientCountsResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackConversationsListParams {
    pub(crate) types: String,
    pub(crate) exclude_archived: bool,
    pub(crate) limit: SafeInteger,
    pub(crate) cursor: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackConversationsListResultData {
    pub(crate) channels: Vec<SlackRoom>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) response_metadata: Option<SlackMetadata>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackConversationsListResult {
    pub(crate) data: SlackConversationsListResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackConversationsMembersParams {
    pub(crate) channel: String,
    pub(crate) limit: SafeInteger,
    pub(crate) cursor: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackConversationsMembersResultData {
    pub(crate) members: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) response_metadata: Option<SlackMetadata>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackConversationsMembersResult {
    pub(crate) data: SlackConversationsMembersResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackConversationsHistoryParams {
    pub(crate) channel: String,
    pub(crate) limit: SafeInteger,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) latest: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) inclusive: Option<bool>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackConversationsHistoryResultData {
    pub(crate) messages: Vec<SlackMessage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) has_more: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) response_metadata: Option<SlackMetadata>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackConversationsHistoryResult {
    pub(crate) data: SlackConversationsHistoryResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum SlackSearchMessagesParamsSort {
    #[serde(rename = "timestamp")]
    Timestamp,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum SlackSearchMessagesParamsSortDir {
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackSearchMessagesParams {
    pub(crate) query: String,
    pub(crate) count: SafeInteger,
    pub(crate) page: SafeInteger,
    pub(crate) sort: SlackSearchMessagesParamsSort,
    pub(crate) sort_dir: SlackSearchMessagesParamsSortDir,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackSearchMessagesResultData {
    pub(crate) messages: SlackMatches,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackSearchMessagesResult {
    pub(crate) data: SlackSearchMessagesResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SlackChatPostMessageParams {
    pub(crate) channel: String,
    pub(crate) text: String,
    pub(crate) client_msg_id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackChatPostMessageResultData {
    pub(crate) ts: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) message: Option<SlackPostedMessage>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackChatPostMessageResult {
    pub(crate) data: SlackChatPostMessageResultData,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoMetadataResult {
    pub(crate) own_id: String,
    pub(crate) has_details: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct KakaoRoomsParams {
    pub(crate) resolve_titles: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoRoomsResult {
    pub(crate) data: Vec<KakaoRoom>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoDetailResult {
    pub(crate) data: KakaoRoom,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoPageResult {
    pub(crate) messages: Vec<AccountMessage>,
    pub(crate) complete: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) next_cursor: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoMembersResult {
    pub(crate) data: Vec<KakaoMember>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoSelfMembersResult {
    pub(crate) data: Vec<KakaoMember>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum KakaoSendResultState {
    #[serde(rename = "Sent")]
    Sent,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoSendResult {
    pub(crate) state: KakaoSendResultState,
    pub(crate) receipt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum TelegramLoadDirectoryParamsList {
    #[serde(rename = "main")]
    Main,
    #[serde(rename = "archive")]
    Archive,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct TelegramLoadDirectoryParams {
    pub(crate) list: TelegramLoadDirectoryParamsList,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramLoadDirectoryResult {
    pub(crate) complete: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum TelegramListDirectoryParamsList {
    #[serde(rename = "main")]
    Main,
    #[serde(rename = "archive")]
    Archive,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct TelegramListDirectoryParams {
    pub(crate) list: TelegramListDirectoryParamsList,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramListDirectoryResult {
    pub(crate) ids: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramChatResult {
    pub(crate) chats: Vec<AccountChat>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum TelegramSenderParamsKind {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "chat")]
    Chat,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct TelegramSenderParams {
    pub(crate) kind: TelegramSenderParamsKind,
    pub(crate) id: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramSenderResult {
    pub(crate) name: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramHistoryResult {
    pub(crate) messages: Vec<AccountMessage>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramSearchResult {
    pub(crate) messages: Vec<AccountMessage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) next_offset: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum TelegramSendResultState {
    #[serde(rename = "Sent")]
    Sent,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramSendResult {
    pub(crate) state: TelegramSendResultState,
    pub(crate) receipt: String,
    pub(crate) messages: Vec<AccountMessage>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum SlackSendFileResultV0State {
    #[serde(rename = "Sent")]
    Sent,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackSendFileResultV0 {
    pub(crate) state: SlackSendFileResultV0State,
    pub(crate) receipt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum SlackSendFileResultV1State {
    #[serde(rename = "Failed")]
    Failed,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct SlackSendFileResultV1 {
    pub(crate) state: SlackSendFileResultV1State,
    pub(crate) reason: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub(crate) enum SlackSendFileResult {
    V0(SlackSendFileResultV0),
    V1(SlackSendFileResultV1),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum KakaoSendFileResultV0State {
    #[serde(rename = "Sent")]
    Sent,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoSendFileResultV0 {
    pub(crate) state: KakaoSendFileResultV0State,
    pub(crate) receipt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum KakaoSendFileResultV1State {
    #[serde(rename = "Failed")]
    Failed,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct KakaoSendFileResultV1 {
    pub(crate) state: KakaoSendFileResultV1State,
    pub(crate) reason: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub(crate) enum KakaoSendFileResult {
    V0(KakaoSendFileResultV0),
    V1(KakaoSendFileResultV1),
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum TelegramSendFileResultV0State {
    #[serde(rename = "Sent")]
    Sent,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramSendFileResultV0 {
    pub(crate) state: TelegramSendFileResultV0State,
    pub(crate) receipt: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) enum TelegramSendFileResultV1State {
    #[serde(rename = "Failed")]
    Failed,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct TelegramSendFileResultV1 {
    pub(crate) state: TelegramSendFileResultV1State,
    pub(crate) reason: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub(crate) enum TelegramSendFileResult {
    V0(TelegramSendFileResultV0),
    V1(TelegramSendFileResultV1),
}
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag = "op", deny_unknown_fields)]
pub(crate) enum PrimitiveRequest {
    #[serde(rename = "slack.users.list")]
    SlackUsersList { params: SlackUsersListParams },
    #[serde(rename = "slack.users.info")]
    SlackUsersInfo { params: SlackUsersInfoParams },
    #[serde(rename = "slack.client.counts")]
    SlackClientCounts { params: SlackClientCountsParams },
    #[serde(rename = "slack.conversations.list")]
    SlackConversationsList {
        params: SlackConversationsListParams,
    },
    #[serde(rename = "slack.conversations.members")]
    SlackConversationsMembers {
        params: SlackConversationsMembersParams,
    },
    #[serde(rename = "slack.conversations.history")]
    SlackConversationsHistory {
        params: SlackConversationsHistoryParams,
    },
    #[serde(rename = "slack.search.messages")]
    SlackSearchMessages { params: SlackSearchMessagesParams },
    #[serde(rename = "slack.chat.postMessage")]
    SlackChatPostMessage { params: SlackChatPostMessageParams },
    #[serde(rename = "kakao_metadata")]
    KakaoMetadata {},
    #[serde(rename = "kakao_rooms")]
    KakaoRooms { params: KakaoRoomsParams },
    #[serde(rename = "kakao_detail")]
    KakaoDetail { chat_id: String },
    #[serde(rename = "kakao_page")]
    KakaoPage {
        chat_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cursor: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        limit: Option<SafeInteger>,
    },
    #[serde(rename = "kakao_members")]
    KakaoMembers { chat_id: String, ids: Vec<String> },
    #[serde(rename = "kakao_self_members")]
    KakaoSelfMembers { chat_id: String },
    #[serde(rename = "kakao_send")]
    KakaoSend { chat_id: String, body: String },
    #[serde(rename = "telegram_load_directory")]
    TelegramLoadDirectory {
        params: TelegramLoadDirectoryParams,
        limit: SafeInteger,
    },
    #[serde(rename = "telegram_list_directory")]
    TelegramListDirectory {
        params: TelegramListDirectoryParams,
        limit: SafeInteger,
    },
    #[serde(rename = "telegram_chat")]
    TelegramChat { chat_id: String },
    #[serde(rename = "telegram_sender")]
    TelegramSender { params: TelegramSenderParams },
    #[serde(rename = "telegram_history")]
    TelegramHistory {
        chat_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        message_id: Option<String>,
        limit: SafeInteger,
    },
    #[serde(rename = "telegram_search")]
    TelegramSearch {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        chat_id: Option<String>,
        query: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cursor: Option<String>,
        limit: SafeInteger,
    },
    #[serde(rename = "telegram_send")]
    TelegramSend { chat_id: String, body: String },
    #[serde(rename = "slack_send_file")]
    SlackSendFile {
        chat_id: String,
        file: LocalAttachment,
    },
    #[serde(rename = "kakao_send_file")]
    KakaoSendFile {
        chat_id: String,
        file: LocalAttachment,
    },
    #[serde(rename = "telegram_send_file")]
    TelegramSendFile {
        chat_id: String,
        file: LocalAttachment,
    },
    #[serde(rename = "batch")]
    Batch { requests: Vec<PrimitiveRequest> },
}
#[derive(Debug)]
pub(crate) enum PrimitiveResult {
    SlackUsersList(SlackUsersListResult),
    SlackUsersInfo(SlackUsersInfoResult),
    SlackClientCounts(SlackClientCountsResult),
    SlackConversationsList(SlackConversationsListResult),
    SlackConversationsMembers(SlackConversationsMembersResult),
    SlackConversationsHistory(SlackConversationsHistoryResult),
    SlackSearchMessages(SlackSearchMessagesResult),
    SlackChatPostMessage(SlackChatPostMessageResult),
    KakaoMetadata(KakaoMetadataResult),
    KakaoRooms(KakaoRoomsResult),
    KakaoDetail(KakaoDetailResult),
    KakaoPage(KakaoPageResult),
    KakaoMembers(KakaoMembersResult),
    KakaoSelfMembers(KakaoSelfMembersResult),
    KakaoSend(KakaoSendResult),
    TelegramLoadDirectory(TelegramLoadDirectoryResult),
    TelegramListDirectory(TelegramListDirectoryResult),
    TelegramChat(TelegramChatResult),
    TelegramSender(TelegramSenderResult),
    TelegramHistory(TelegramHistoryResult),
    TelegramSearch(TelegramSearchResult),
    TelegramSend(TelegramSendResult),
    SlackSendFile(SlackSendFileResult),
    KakaoSendFile(KakaoSendFileResult),
    TelegramSendFile(TelegramSendFileResult),
    Batch(Vec<PrimitiveResult>),
}
impl PrimitiveRequest {
    pub(crate) fn decode_result(
        &self,
        value: serde_json::Value,
    ) -> Result<PrimitiveResult, serde_json::Error> {
        Ok(match self {
            Self::SlackUsersList { .. } => {
                PrimitiveResult::SlackUsersList(serde_json::from_value(value)?)
            }
            Self::SlackUsersInfo { .. } => {
                PrimitiveResult::SlackUsersInfo(serde_json::from_value(value)?)
            }
            Self::SlackClientCounts { .. } => {
                PrimitiveResult::SlackClientCounts(serde_json::from_value(value)?)
            }
            Self::SlackConversationsList { .. } => {
                PrimitiveResult::SlackConversationsList(serde_json::from_value(value)?)
            }
            Self::SlackConversationsMembers { .. } => {
                PrimitiveResult::SlackConversationsMembers(serde_json::from_value(value)?)
            }
            Self::SlackConversationsHistory { .. } => {
                PrimitiveResult::SlackConversationsHistory(serde_json::from_value(value)?)
            }
            Self::SlackSearchMessages { .. } => {
                PrimitiveResult::SlackSearchMessages(serde_json::from_value(value)?)
            }
            Self::SlackChatPostMessage { .. } => {
                PrimitiveResult::SlackChatPostMessage(serde_json::from_value(value)?)
            }
            Self::KakaoMetadata { .. } => {
                PrimitiveResult::KakaoMetadata(serde_json::from_value(value)?)
            }
            Self::KakaoRooms { .. } => PrimitiveResult::KakaoRooms(serde_json::from_value(value)?),
            Self::KakaoDetail { .. } => {
                PrimitiveResult::KakaoDetail(serde_json::from_value(value)?)
            }
            Self::KakaoPage { .. } => PrimitiveResult::KakaoPage(serde_json::from_value(value)?),
            Self::KakaoMembers { .. } => {
                PrimitiveResult::KakaoMembers(serde_json::from_value(value)?)
            }
            Self::KakaoSelfMembers { .. } => {
                PrimitiveResult::KakaoSelfMembers(serde_json::from_value(value)?)
            }
            Self::KakaoSend { .. } => PrimitiveResult::KakaoSend(serde_json::from_value(value)?),
            Self::TelegramLoadDirectory { .. } => {
                PrimitiveResult::TelegramLoadDirectory(serde_json::from_value(value)?)
            }
            Self::TelegramListDirectory { .. } => {
                PrimitiveResult::TelegramListDirectory(serde_json::from_value(value)?)
            }
            Self::TelegramChat { .. } => {
                PrimitiveResult::TelegramChat(serde_json::from_value(value)?)
            }
            Self::TelegramSender { .. } => {
                PrimitiveResult::TelegramSender(serde_json::from_value(value)?)
            }
            Self::TelegramHistory { .. } => {
                PrimitiveResult::TelegramHistory(serde_json::from_value(value)?)
            }
            Self::TelegramSearch { .. } => {
                PrimitiveResult::TelegramSearch(serde_json::from_value(value)?)
            }
            Self::TelegramSend { .. } => {
                PrimitiveResult::TelegramSend(serde_json::from_value(value)?)
            }
            Self::SlackSendFile { .. } => {
                PrimitiveResult::SlackSendFile(serde_json::from_value(value)?)
            }
            Self::KakaoSendFile { .. } => {
                PrimitiveResult::KakaoSendFile(serde_json::from_value(value)?)
            }
            Self::TelegramSendFile { .. } => {
                PrimitiveResult::TelegramSendFile(serde_json::from_value(value)?)
            }
            Self::Batch { requests } => {
                #[derive(serde::Deserialize)]
                struct BatchResult {
                    results: Vec<serde_json::Value>,
                }
                let batch: BatchResult = serde_json::from_value(value)?;
                if batch.results.len() != requests.len() {
                    return Err(<serde_json::Error as serde::de::Error>::custom(
                        "batch length mismatch",
                    ));
                }
                PrimitiveResult::Batch(
                    requests
                        .iter()
                        .zip(batch.results)
                        .map(|(r, v)| r.decode_result(v))
                        .collect::<Result<_, _>>()?,
                )
            }
        })
    }
}
