/** Regenerate both language declarations from the private primitive wire schema. */
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
const root = new URL("../", import.meta.url);
type Schema = string | { fields: Record<string, Schema> } | { optional: Schema } | { array: Schema } | { enum: string[] } | { union: Schema[] };
const schema = JSON.parse(readFileSync(new URL("packages/accounts/schema/primitives.json", root), "utf8")) as {
  types: Record<string, Schema>; operations: Record<string, { request: { fields: Record<string, Schema> }; result: Schema }>;
};
const pascal = (s: string) => s.split(/[._]/).map(p => p[0]!.toUpperCase() + p.slice(1)).join("");
function ts(s: Schema): string {
  if (typeof s === "string") return (s === "integer" || s === "file_size") ? "number" : s === "nonempty" ? "string" : s;
  if ("optional" in s) return `(${ts(s.optional)}) | null`;
  if ("array" in s) return `Array<${ts(s.array)}>`;
  if ("enum" in s) return s.enum.map(v => JSON.stringify(v)).join(" | ");
  if ("union" in s) return s.union.map(ts).join(" | ");
  return `{ ${Object.entries(s.fields).map(([k,v]) => `${k}${typeof v !== "string" && "optional" in v ? "?" : ""}: ${ts(v)}`).join("; ")} }`;
}
let out = "// Generated by scripts/generate-account-contract.ts. Edit schema/primitives.json.\n";
for (const [name, s] of Object.entries(schema.types)) out += `export type ${name} = ${ts(s)};\n`;
for (const [op, def] of Object.entries(schema.operations)) {
  out += `export type ${pascal(op)}Request = { op: ${JSON.stringify(op)} } & ${ts(def.request)};\n`;
  out += `export type ${pascal(op)}Result = ${ts(def.result)};\n`;
}
out += `export interface PrimitiveResults {\n${Object.keys(schema.operations).map(op => `  ${JSON.stringify(op)}: ${pascal(op)}Result;`).join("\n")}\n}\n`;
out += `export type PrimitiveRequest = ${Object.keys(schema.operations).map(op => pascal(op)+"Request").join(" | ")};\n`;
out += 'export type ReadRequest = Exclude<PrimitiveRequest, { op: "kakao_send" | "telegram_send" | "slack.chat.postMessage" | "slack_send_file" | "kakao_send_file" | "telegram_send_file" }>;\n';
out += 'export type AccountRequest = PrimitiveRequest | { op: "batch"; requests: ReadRequest[] };\n';
out += 'export type AccountResult = PrimitiveResults[keyof PrimitiveResults] | { results: PrimitiveResults[ReadRequest["op"]][] };\n';
out += 'export type ResultFor<R extends AccountRequest> = R extends { op: "batch" } ? { results: PrimitiveResults[ReadRequest["op"]][] } : R extends PrimitiveRequest ? PrimitiveResults[R["op"]] : never;\n';
const declarations: string[] = [];
function rust(s: Schema, name: string, strict: boolean): string {
  if (typeof s === "string") return ({string:"String", nonempty:"String", number:"f64", integer:"SafeInteger", file_size:"SafeInteger", boolean:"bool"} as Record<string,string>)[s] ?? s;
  if ("optional" in s) return `Option<${rust(s.optional,name,strict)}>`;
  if ("array" in s) return `Vec<${rust(s.array,name,strict)}>`;
  const derive = '#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n';
  if ("enum" in s) {
    declarations.push(`${derive}pub(crate) enum ${name} {\n${s.enum.map(v => `    #[serde(rename = ${JSON.stringify(v)})]\n    ${pascal(v)},`).join("\n")}\n}`);
  } else if ("union" in s) {
    const variants = s.union.map((v,i) => `    V${i}(${rust(v,`${name}V${i}`,strict)}),`);
    declarations.push(`${derive}#[serde(untagged)]\npub(crate) enum ${name} {\n${variants.join("\n")}\n}`);
  } else {
    const fields = Object.entries(s.fields).map(([k,v]) => {
      const optional = typeof v !== "string" && "optional" in v;
      return `${optional ? '    #[serde(default, skip_serializing_if = "Option::is_none")]\n' : ''}    pub(crate) ${k === "type" ? "r#type" : k}: ${rust(v, name+pascal(k), strict)},`;
    });
    declarations.push(`${derive}${strict ? '#[serde(deny_unknown_fields)]\n' : ''}pub(crate) struct ${name} {\n${fields.join("\n")}\n}`);
  }
  return name;
}
for (const [name, s] of Object.entries(schema.types)) rust(s,name,false);
const variants: string[] = [], resultVariants: string[] = [], resultMatches: string[] = [];
for (const [op, def] of Object.entries(schema.operations)) {
  const name = pascal(op);
  const fields = Object.entries(def.request.fields).map(([k,v]) => {
    const optional = typeof v !== "string" && "optional" in v;
    return `${optional ? '        #[serde(default, skip_serializing_if = "Option::is_none")]\n' : ''}        ${k}: ${rust(v,name+pascal(k),true)},`;
  });
  variants.push(`    #[serde(rename = ${JSON.stringify(op)})]\n    ${name} {\n${fields.join("\n")}\n    },`);
  rust(def.result, name+"Result", false);
  resultVariants.push(`    ${name}(${name}Result),`);
  resultMatches.push(`            Self::${name} { .. } => PrimitiveResult::${name}(serde_json::from_value(value)?),`);
}
let rs = '// Generated by scripts/generate-account-contract.ts. Edit packages/accounts/schema/primitives.json.\n#![allow(dead_code)]\n';
rs += `#[derive(Debug, Clone, serde::Serialize)]\npub(crate) struct SafeInteger(u64);\nimpl<'de> serde::Deserialize<'de> for SafeInteger {\n    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {\n        let n = <f64 as serde::Deserialize>::deserialize(deserializer)?;\n        if !n.is_finite() || n < 0.0 || n.fract() != 0.0 || n > 9_007_199_254_740_991.0 { return Err(serde::de::Error::custom("unsafe integer")); }\n        Ok(Self(n as u64))\n    }\n}\n`;
rs += declarations.join("\n\n") + '\n';
rs += '#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n#[serde(tag = "op", deny_unknown_fields)]\npub(crate) enum PrimitiveRequest {\n' + variants.join("\n") + '\n    #[serde(rename = "batch")]\n    Batch { requests: Vec<PrimitiveRequest> },\n}\n';
rs += '#[derive(Debug)]\npub(crate) enum PrimitiveResult {\n'+resultVariants.join("\n")+'\n    Batch(Vec<PrimitiveResult>),\n}\n';
rs += 'impl PrimitiveRequest {\n    pub(crate) fn decode_result(&self, value: serde_json::Value) -> Result<PrimitiveResult, serde_json::Error> {\n        Ok(match self {\n'+resultMatches.join("\n")+'\n            Self::Batch { requests } => {\n                #[derive(serde::Deserialize)] struct BatchResult { results: Vec<serde_json::Value> }\n                let batch: BatchResult = serde_json::from_value(value)?;\n                if batch.results.len() != requests.len() { return Err(<serde_json::Error as serde::de::Error>::custom("batch length mismatch")); }\n                PrimitiveResult::Batch(requests.iter().zip(batch.results).map(|(r,v)|r.decode_result(v)).collect::<Result<_,_>>()?)\n            }\n        })\n    }\n}\n';
const rustfmt = process.env.RUSTFMT ?? Bun.which("rustfmt") ?? `${homedir()}/.cargo/bin/rustfmt`;
const formatted = Bun.spawnSync({ cmd: [rustfmt, "--edition", "2024"], stdin: Buffer.from(rs) });
if (formatted.exitCode !== 0) throw new Error(formatted.stderr.toString());
rs = formatted.stdout.toString();
for (const [file, content] of [["packages/accounts/src/generated.ts",out], ["crates/inboxd-daemon/src/accounts_backend/contract_generated.rs",rs]]) {
  const path = new URL(file!, root);
  if (process.argv.includes("--check")) {
    if (readFileSync(path,"utf8") !== content) throw new Error(`Stale generated contract: ${file}`);
  } else writeFileSync(path,content!);
}
